version: '3'

env:
  ENV: development

dotenv: ['.env.{{.ENV}}']

tasks:
  startUp:
    deps: [migrateUp]
    cmds:
      - pnpm hasura metadata apply
      - pnpm dev

  migrateUp:
    cmds:
      - dbmate up

  migrateDown:
    cmds:
      - dbmate down

  gqlGenerate:
    cmds:
      - npm run graphql-codegen {{.CLI_ARGS}}
